

git-intro.pdf: git-intro.tex
	pdflatex git-intro.tex


clean:
	rm -rf git-intro.aux git-intro.log git-intro.nav
	rm -rf git-intro.out git-intro.pdf git-intro.snm
	rm -rf git-intro.synctex.gz git-intro.toc git-intro.vrb

