introduction_to_NEURON.pdf: introduction_to_NEURON.rst
	#rst2pdf -o introduction_to_NEURON.pdf -b2 -s slides.style  introduction_to_NEURON.rst
	rst2pdf -o introduction_to_NEURON.pdf -b2 -s slides.style  introduction_to_NEURON.rst

clean:
	rm introduction_to_NEURON.pdf
